os: linux
language: java
jdk:
  - openjdk8
cache:
  directories:
    - "~/.m2/repository"
deploy:
  - provider: script
    script: assets/travis/deploy.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: assets/travis/deploy.sh
    skip_cleanup: true
    on:
      tags: true