language: java
jdk:
  - openjdk8
cache:
  directories:
    - "~/.m2/repository"
before_deploy:
  - mkdir -p ${GPG_DIR}
  - openssl aes-256-cbc -K $encrypted_cd1337d2ab17_key -iv $encrypted_cd1337d2ab17_iv -in travis/gpg.asc.enc -out ${GPG_DIR}/gpg.asc -d
deploy:
  - provider: script
    script: travis/deploy.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: travis/deploy.sh
    skip_cleanup: true
    on:
      tags: true
after_deploy:
  - rm -rf ${GPG_DIR}