name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Package Caching
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Verify
        run: mvn clean verify -B -U
  snapshot:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'
    name: Publish SNAPSHOT
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Maven Package Caching
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Publish SNAPSHOT Artifacts
        run: mvn deploy --settings ./.mvn/settings/mvn-settings.xml -B -U -P oss-snapshot -DskipTests=true
        env:
          SONATYPE_JIRA_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_JIRA_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
