name: Release
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish RELEASE
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Import GPG Signing Key
        run: echo ${{ secrets.GPG_SIGNING_KEY }} | base64 --decode | gpg --import --batch --no-tty --yes
      - name: Publish RELEASE Artifacts
        run: mvn deploy --settings ./.mvn/settings/mvn-settings.xml -B -U -P oss-release -DskipTests=true
        env:
          SONATYPE_JIRA_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_JIRA_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
